# Use the official Flutter lints as a base
include: package:flutter_lints/flutter.yaml

analyzer:
  # Treat missing package imports as errors
  errors:
    missing_required_param: error
    missing_return: error
    undefined_identifier: error
    unused_local_variable: warning
    dead_code: warning
    type_annotate_public_apis: warning
    prefer_const_literals_to_create_immutables: warning

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Flutter best practices
    avoid_print: false
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
    always_declare_return_types: true
    always_use_package_imports: false
    annotate_overrides: true
    avoid_unused_constructor_parameters: true

    # Readability
    camel_case_types: true
    constant_identifier_names: true
    non_constant_identifier_names: false
    prefer_single_quotes: true
    sort_constructors_first: true
    lines_longer_than_80_chars: false

    # Safety
    avoid_null_checks_in_equality_operators: true
    avoid_returning_null: true
    null_check_on_nullable_type_parameter: true
