# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats. Uncomment to disable.
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# This loads the Flutter CocoaPods helper
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), __dir__)

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # This actually adds Flutter pods
  install_all_flutter_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Exclude arm64 for simulator (common for Apple Silicon)
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
