platform :ios, '13.0'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  raise "Generated.xcconfig must exist. Run 'flutter pub get' first." unless File.exist?(generated_xcode_build_settings_path)
  File.expand_path(File.join('..', '..', 'flutter'), generated_xcode_build_settings_path)
end

require File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper'))

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_ios_podfile_setup

  # Add any extra pods here
end
